# Your workflow name
name: Deploy to Render

# Run workflow on every push to main branch
on:
  push:
    branches: [main]

# Your workflows jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository
      - name: Checkout
        uses: actions/checkout@v2

      # Deploy to Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}